USE UNIVER;
--TASK1
EXEC SP_HELPINDEX 'AUDITORIUM_TYPE'
EXEC SP_HELPINDEX 'AUDITORIUM'
EXEC SP_HELPINDEX 'FACULTY'
EXEC SP_HELPINDEX 'GROUPS'
EXEC SP_HELPINDEX 'PROFESSION'
EXEC SP_HELPINDEX 'PROGRESS'
EXEC SP_HELPINDEX 'PULPIT'
EXEC SP_HELPINDEX 'STUDENT'
EXEC SP_HELPINDEX 'SUBJECT'
EXEC SP_HELPINDEX 'TEACHER'

CREATE TABLE #MyTable (CC INT, TF VARCHAR(20))
SET NOCOUNT ON;
DECLARE @a INT = 0;
WHILE @a < 1000
BEGIN 
	INSERT #MyTable
	VALUES (@a, 'Строка' + CAST(@a AS varchar(20)))
	SET @a += 1;
END

SELECT COUNT(*)[Количество строк] FROM #MyTable
SELECT * FROM #MyTable

CHECKPOINT;
DBCC DROPCLEANBUFFERS;

drop index #MyTable_CC_IDX ON #MyTable

use tempdb

CREATE CLUSTERED INDEX #MyTable_CC_IDX ON #MyTable(CC ASC)
go
EXEC SP_HELPINDEX '#MyTable'
go


SELECT * FROM #MyTable WHERE CC BETWEEN 200 AND 500

--TASK2
CREATE TABLE #MyTable2(CC INT IDENTITY(1,1), TKEY INT, TF VARCHAR(100));
SET NOCOUNT ON;
DECLARE @i INT = 0;
WHILE @i < 30000
BEGIN
  INSERT #MyTable2(TKEY, TF)
  VALUES(FLOOR(20000 * RAND()), 'LINE');
  SET @i = @i + 1;
END;

SELECT COUNT(*)[Количество  строк] FROM #MyTable2;
SELECT * FROM #MyTable2;

drop index #MyTable2_IDX on #MyTable2

CREATE INDEX #MyTable2_IDX ON #MyTable2(TKEY, CC);
EXEC SP_HELPINDEX '#MyTable2';

SELECT * FROM #MyTable2 WHERE TKEY > 1500 AND CC < 4500;  
SELECT * FROM #MyTable2 ORDER BY TKEY, CC;
SELECT * FROM #MyTable2 WHERE TKEY = 556 AND CC > 3;

--TASK3
CREATE TABLE #MyTable3(CC INT IDENTITY(1,1), TKEY INT, TF VARCHAR(20))
SET NOCOUNT ON;
DECLARE @b INT = 0;
WHILE @b < 30000
BEGIN 
	INSERT #MyTable3 (TKEY,TF)
	VALUES(FLOOR(20000*RAND()), 'строка');
	SET @b = @b + 1;
END;

SELECT COUNT(*)[Количество строк] FROM #MyTable3
SELECT * FROM #MyTable3

CREATE INDEX #MyTable3_IDX ON #MyTable3(TKEY) INCLUDE(CC)
EXEC SP_HELPINDEX '#MyTable3'

SELECT CC FROM #MyTable3 WHERE TKEY > 17500

--TASK4
CREATE TABLE #MyTable4(CC INT IDENTITY(1,1), TKEY INT, TF VARCHAR(20))
SET NOCOUNT ON;
DECLARE @x INT = 0;
WHILE @x < 30000
BEGIN 
	INSERT #MyTable4 (TKEY,TF)
	VALUES(FLOOR(20000*RAND()), 'LINE');
	SET @x = @x + 1;
END;

SELECT COUNT(*)[Количество строк] FROM #MyTable4
SELECT * FROM #MyTable4

CREATE INDEX #MyTable4_IDX ON #MyTable4(TKEY) WHERE (TKEY>8000 AND TKEY<18000)
EXEC SP_HELPINDEX '#MyTable4'

SELECT TKEY FROM #MyTable4 WHERE TKEY BETWEEN 6000 AND 12000
SELECT TKEY FROM #MyTable4 WHERE TKEY BETWEEN 12000 AND 16000
SELECT TKEY FROM #MyTable4 WHERE TKEY=12000

--TASK5
CREATE TABLE #MyTable5(CC INT IDENTITY(1,1), TKEY INT, TF VARCHAR(20))
SET NOCOUNT ON;
DECLARE @y INT = 0;
WHILE @y < 1000
BEGIN 
	INSERT #MyTable5 (TKEY,TF)
	VALUES(FLOOR(20000*RAND()), 'LINE');
	SET @y = @y + 1;
END;

SELECT COUNT(*)[Количество строк] FROM #MyTable5
SELECT * FROM #MyTable5

CREATE INDEX #MyTable5_IDX ON #MyTable5(TKEY)
EXEC SP_HELPINDEX '#MyTable5'

SELECT name [Индекс], avg_fragmentation_in_percent [Фрагментация (%)]
FROM sys.dm_db_index_physical_stats(DB_ID(N'TEMPDB'), 
OBJECT_ID(N'#MyTable5'), NULL, NULL, NULL) ss  JOIN sys.indexes ii 
ON ss.object_id = ii.object_id and ss.index_id = ii.index_id  
WHERE name is not null;

DELETE FROM #MyTable5;
DECLARE @r INT = 0;
WHILE @r < 65000
BEGIN 
	INSERT #MyTable5 (TKEY,TF)
	VALUES(FLOOR(20000*RAND()), 'LINE');
	SET @r = @r + 1;
END;--92,4050632911392

ALTER INDEX #MyTable5_IDX ON #MyTable5 REORGANIZE--0,689655172413793

ALTER INDEX #MyTable5_IDX ON #MyTable5 REBUILD WITH (ONLINE = OFF)--0,0


--TASK6
CREATE TABLE #MyTable6(CC INT IDENTITY(1,1), TKEY INT, TF VARCHAR(20))
SET NOCOUNT ON;
DECLARE @t INT = 0;
WHILE @t < 1000
BEGIN 
	INSERT #MyTable6 (TKEY,TF)
	VALUES(FLOOR(20000*RAND()), 'LINE');
	SET @t = @t + 1;
END;

SELECT COUNT(*)[Количество строк] FROM #MyTable6
SELECT * FROM #MyTable6

CREATE INDEX #MyTable6_IDX_1 ON #MyTable6(TKEY) WITH (FILLFACTOR = 48)
CREATE INDEX #MyTable6_IDX_2 ON #MyTable6(TKEY) WITH (FILLFACTOR = 52)
CREATE INDEX #MyTable6_IDX_3 ON #MyTable6(TKEY)
EXEC SP_HELPINDEX '#MyTable6'

SELECT name [Индекс], avg_fragmentation_in_percent [Фрагментация (%)]
FROM sys.dm_db_index_physical_stats(DB_ID(N'TEMPDB'), 
OBJECT_ID(N'#MyTable6'), NULL, NULL, NULL) ss  JOIN sys.indexes ii 
ON ss.object_id = ii.object_id and ss.index_id = ii.index_id  
WHERE name is not null;

INSERT TOP(1000) #MyTable6(TKEY, TF) SELECT TKEY, TF FROM #MyTable6