--1 задание
SELECT 
    AUDITORIUM.AUDITORIUM, 
    AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM 
INNER JOIN AUDITORIUM_TYPE 
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;

--2 задание
SELECT 
    AUDITORIUM.AUDITORIUM, 
    AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM 
INNER JOIN AUDITORIUM_TYPE 
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%';

--/////////
--3 задание
SELECT 
    FACULTY.FACULTY_NAME AS "Факультет",
    PULPIT.PULPIT_NAME AS "Кафедра",
    GROUPS.PROFESSION AS "Специальность",
    SUBJECT.SUBJECT_NAME AS "Дисциплина",
    STUDENT.NAME AS "Имя Студента",
    CASE 
        WHEN PROGRESS.NOTE = 6 THEN 'шесть'
        WHEN PROGRESS.NOTE = 7 THEN 'семь'
        WHEN PROGRESS.NOTE = 8 THEN 'восемь'
    END AS "Оценка"
FROM PROGRESS
INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
INNER JOIN PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
WHERE PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY PROGRESS.NOTE DESC;

--/////////
--4 задание
SELECT PL.PULPIT_NAME[Кафедра], isnull(TCH.TEACHER_NAME, '***')[Преподователь]
	FROM PULPIT AS PL LEFT OUTER JOIN TEACHER AS TCH
	ON PL.PULPIT = TCH.PULPIT

--/////////
--5 задание
SELECT PULPIT.PULPIT, TEACHER.TEACHER_NAME
	FROM PULPIT FULL OUTER JOIN TEACHER
	ON PULPIT.PULPIT = TEACHER.PULPIT
	WHERE TEACHER.TEACHER IS NULL

use Univer

SELECT PULPIT.PULPIT, TEACHER.TEACHER_NAME
	FROM PULPIT FULL OUTER JOIN TEACHER
	ON TEACHER.PULPIT  = PULPIT.PULPIT
	WHERE TEACHER.TEACHER IS NOT NULL

use Univer

SELECT PULPIT.PULPIT, TEACHER.TEACHER_NAME
	FROM PULPIT FULL OUTER JOIN TEACHER
	ON PULPIT.PULPIT = TEACHER.PULPIT

--////////
--6 задание
use Univer

SELECT T1.AUDITORIUM, T2.AUDITORIUM_TYPENAME
	FROM AUDITORIUM AS T1 CROSS JOIN AUDITORIUM_TYPE AS T2 
	WHERE T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE;
