use UNIVER;

SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÈÒ')
GROUP BY G.FACULTY, G.PROFESSION, P.SUBJECT;

SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÈÒ')
GROUP BY ROLLUP (G.FACULTY, G.PROFESSION, P.SUBJECT);

SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÈÒ')
GROUP BY CUBE (G.FACULTY, G.PROFESSION, P.SUBJECT);

--////
SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÈÒ')
GROUP BY G.FACULTY, G.PROFESSION, P.SUBJECT
UNION
SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÕÒèÒ')
GROUP BY G.FACULTY, G.PROFESSION, P.SUBJECT


SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÈÒ')
GROUP BY G.FACULTY, G.PROFESSION, P.SUBJECT
UNION ALL
SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÕÒèÒ')
GROUP BY G.FACULTY, G.PROFESSION, P.SUBJECT

--////
SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÈÒ')
GROUP BY G.FACULTY, G.PROFESSION, P.SUBJECT
INTERSECT
SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÈÒ')
GROUP BY G.FACULTY, G.PROFESSION, P.SUBJECT

SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÈÒ')
GROUP BY G.FACULTY, G.PROFESSION, P.SUBJECT
EXCEPT
SELECT G.FACULTY, G.PROFESSION, P.SUBJECT, AVG(P.NOTE) AS AVG_NOTE
FROM GROUPS G
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP 
JOIN PROGRESS P ON P.IDSTUDENT = S.IDSTUDENT
WHERE G.FACULTY IN ('ÕÒèÒ')
GROUP BY G.FACULTY, G.PROFESSION, P.SUBJECT