--1 TASK
--некоррелируемый
use UNIVER
select 
	PULPIT_NAME
from PULPIT
where FACULTY IN (
	SELECT FACULTY
	FROM PROFESSION
	WHERE PROFESSION_NAME LIKE '%технология%' 
       OR PROFESSION_NAME LIKE '%технологии%'
	   );

--иннер джоин	
USE UNIVER;
SELECT P.PULPIT_NAME
FROM PULPIT P
INNER JOIN (
    SELECT DISTINCT FACULTY
    FROM PROFESSION
    WHERE PROFESSION_NAME LIKE '%технология%' 
       OR PROFESSION_NAME LIKE '%технологии%'
) PR ON P.FACULTY = PR.FACULTY;

USE UNIVER;
--без исп подзапроса
SELECT DISTINCT P.PULPIT_NAME
FROM PULPIT P
INNER JOIN FACULTY F ON P.FACULTY = F.FACULTY
INNER JOIN PROFESSION PR ON F.FACULTY = PR.FACULTY
WHERE PR.PROFESSION_NAME LIKE '%технология%' 
   OR PR.PROFESSION_NAME LIKE '%технологии%';

--4 TASK

USE UNIVER;
--список аудиторий самых больших вместимостей 
SELECT A.AUDITORIUM, A.AUDITORIUM_TYPE, A.AUDITORIUM_CAPACITY, A.AUDITORIUM_NAME
FROM AUDITORIUM A
WHERE A.AUDITORIUM_CAPACITY = (
    SELECT TOP 1 A1.AUDITORIUM_CAPACITY
    FROM AUDITORIUM A1
    WHERE A1.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE
    ORDER BY A1.AUDITORIUM_CAPACITY DESC
)
ORDER BY A.AUDITORIUM_CAPACITY DESC;

--5 TASK
--список наименований факультетов на котором нет ни одной кафедры
SELECT F.FACULTY_NAME
FROM FACULTY F
WHERE NOT EXISTS (
    SELECT 1 
    FROM PULPIT P
    WHERE P.FACULTY = F.FACULTY
);

--6 таск

USE UNIVER;

SELECT 
    (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = 'ОАиП') AS AVG_OAIP,
    (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = 'БД') AS AVG_BD,
    (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = 'СУБД') AS AVG_SUBD;

--7 task

USE UNIVER;

SELECT IDSTUDENT, SUBJECT, NOTE
FROM PROGRESS
WHERE NOTE > ALL (
    SELECT NOTE
    FROM PROGRESS
    WHERE SUBJECT = 'ОАиП'
);

--8 task

USE UNIVER;

SELECT IDSTUDENT, SUBJECT, NOTE
FROM PROGRESS
WHERE NOTE > ANY (
    SELECT NOTE
    FROM PROGRESS
    WHERE SUBJECT = 'ОАиП'
);

