USE UNIVER;
SELECT AUDITORIUM, AUDITORIUM_TYPE
FROM AUDITORIUM
WHERE AUDITORIUM_TYPE IN (
	SELECT AUDITORIUM_TYPE 
	FROM AUDITORIUM_TYPE
	WHERE AUDITORIUM_TYPENAME LIKE 'Лекционная%'
	);

USE UNIVER;
SELECT AUDITORIUM, AUDITORIUM_TYPE
FROM AUDITORIUM A
WHERE EXISTS (
	SELECT 1
	FROM AUDITORIUM_TYPE T
	WHERE T.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE AND
	T.AUDITORIUM_TYPENAME LIKE 'Лекционная%'
	);

USE UNIVER;
SELECT AUDITORIUM, AUDITORIUM_TYPE , AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM_TYPE IN (
	SELECT AUDITORIUM_TYPE
	FROM AUDITORIUM_TYPE
	WHERE AUDITORIUM_TYPENAME like '%а%'
	);



USE UNIVER;
SELECT AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM A
WHERE EXISTS (
	SELECT 1
	FROM AUDITORIUM_TYPE T
	WHERE T.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE AND AUDITORIUM_TYPENAME LIKE '%а%'
	);