--1/2
USE UNIVER;
select 
	A1.AUDITORIUM_TYPENAME,
	MAX(A.AUDITORIUM_CAPACITY) AS [MAX capacity], 
	MIN(A.AUDITORIUM_CAPACITY) AS [MIN capacity], 
	AVG(A.AUDITORIUM_CAPACITY) AS [AVG capacity],
	SUM(A.AUDITORIUM_CAPACITY) AS [SUM capacity],
	COUNT(*) AS [AUD QUANTITY]
FROM AUDITORIUM A
INNER JOIN AUDITORIUM_TYPE A1 ON A.AUDITORIUM_TYPE = A1.AUDITORIUM_TYPE
GROUP BY A1.AUDITORIUM_TYPENAME

--3
SELECT 
    CASE
        WHEN (p.NOTE in (4, 5)) THEN '4-5'
        WHEN (p.NOTE in (6, 7)) THEN '6-7'
        WHEN (p.NOTE in (8, 9)) THEN '8-9'
        WHEN (p.NOTE = 10) THEN '10'
    END AS [INTERVAL],
    COUNT(*) AS [QUANTITY]
FROM PROGRESS AS p
GROUP BY 
    CASE
        WHEN (p.NOTE in (4, 5)) THEN '4-5'
        WHEN (p.NOTE in (6, 7)) THEN '6-7'
        WHEN (p.NOTE in (8, 9)) THEN '8-9'
        WHEN (p.NOTE = 10) THEN '10'
    END


--4
SELECT 
    F.FACULTY_NAME AS Факультет,
    G.PROFESSION AS Специальность,
    (YEAR(GETDATE()) - G.YEAR_FIRST) + 1 AS Курс,
    ROUND(CAST(AVG(P.NOTE) AS FLOAT), 2) AS Средняя_оценка
FROM PROGRESS P
INNER JOIN STUDENT S ON P.IDSTUDENT = S.IDSTUDENT
INNER JOIN GROUPS G ON S.IDGROUP = G.IDGROUP
INNER JOIN FACULTY F ON G.FACULTY = F.FACULTY
WHERE P.NOTE IS NOT NULL
GROUP BY 
    F.FACULTY_NAME,
    G.PROFESSION,
    (YEAR(GETDATE()) - G.YEAR_FIRST) + 1
ORDER BY Средняя_оценка DESC;

--6
SELECT 
    F.FACULTY_NAME AS Факультет,
    G.PROFESSION AS Специальность,
    (YEAR(GETDATE()) - G.YEAR_FIRST) + 1 AS Курс,
    ROUND(CAST(AVG(P.NOTE) AS FLOAT), 2) AS Средняя_оценка
FROM PROGRESS P
INNER JOIN STUDENT S ON P.IDSTUDENT = S.IDSTUDENT
INNER JOIN GROUPS G ON S.IDGROUP = G.IDGROUP
INNER JOIN FACULTY F ON G.FACULTY = F.FACULTY
WHERE P.NOTE IS NOT NULL
		AND P.SUBJECT IN ('СУБД','ОАиП')
GROUP BY 
    F.FACULTY_NAME,
    G.PROFESSION,
    (YEAR(GETDATE()) - G.YEAR_FIRST) + 1
ORDER BY Средняя_оценка DESC;


--6
SELECT G.PROFESSION, PR.SUBJECT,
	AVG(PR.NOTE) [AVG NOTE]
	FROM FACULTY AS F 
	INNER JOIN GROUPS AS G ON F.FACULTY = G.FACULTY
	INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
	INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
		WHERE F.FACULTY = 'ТОВ'
		GROUP BY G.PROFESSION, PR.SUBJECT

--7
SELECT P.SUBJECT, COUNT(*) [COUNT STUDENT]
	FROM PROGRESS AS P
	GROUP BY P.SUBJECT, P.NOTE
	HAVING P.NOTE IN (8,9)